# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate as interpolate

Altitudea,H2a,C2H2a,C2H6a,NH2a,NH3a,CNa,HCNa,COa,H2Oa,H2COa,CH3OHa,NOa=np.genfromtxt("Triala.csv",delimiter=",",unpack=True)
Altitudeb,H2b,C2H2b,C2H6b,NH2b,NH3b,CNb,HCNb,COb,H2Ob,H2COb,CH3OHb,NOb=np.genfromtxt("Trialb.csv",delimiter=",",unpack=True)
Altitudec,H2c,C2H2c,C2H6c,NH2c,NH3c,CNc,HCNc,COc,H2Oc,H2COc,CH3OHc,NOc=np.genfromtxt("Trialc.csv",delimiter=",",unpack=True)
Altituded,H2d,C2H2d,C2H6d,NH2d,NH3d,CNd,HCNd,COd,H2Od,H2COd,CH3OHd,NOd=np.genfromtxt("Triald.csv",delimiter=",",unpack=True)

plt.plot(Altitudea,NH2a,label="Kc=1, SSD=1e10, CH4%=1")
plt.plot(Altitudeb,NH2b,label="Kc=1, SSD=1e10, CH4%=2")
plt.plot(Altitudec,NH2c,label="Kc=0.5, SSD=1e-12, CH4%=1")
plt.plot(Altituded,NH2d,label="Kc=0.5, SSD=1e-12, CH4%=2")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH2AltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,NH3a,label="Kc=1, SSD=1e10, CH4%=1")
plt.plot(Altitudeb,NH3b,label="Kc=1, SSD=1e10, CH4%=2")
plt.plot(Altitudec,NH3c,label="Kc=0.5, SSD=1e-12, CH4%=1")
plt.plot(Altituded,NH3d,label="Kc=0.5, SSD=1e-12, CH4%=2")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH3AltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,HCNa,label="Kc=1, SSD=1e10, CH4%=1")
plt.plot(Altitudeb,HCNb,label="Kc=1, SSD=1e10, CH4%=2")
plt.plot(Altitudec,HCNc,label="Kc=0.5, SSD=1e-12, CH4%=1")
plt.plot(Altituded,HCNd,label="Kc=0.5, SSD=1e-12, CH4%=2")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("HCNAltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,CNa,label="Kc=1, SSD=1e10, CH4%=1")
plt.plot(Altitudeb,CNb,label="Kc=1, SSD=1e10, CH4%=2")
plt.plot(Altitudec,CNc,label="Kc=0.5, SSD=1e-12, CH4%=1")
plt.plot(Altituded,CNd,label="Kc=0.5, SSD=1e-12, CH4%=2")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("CNAltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,COa,label="Kc=1, SSD=1e10, CH4%=1")
plt.plot(Altitudeb,COb,label="Kc=1, SSD=1e10, CH4%=2")
plt.plot(Altitudec,COc,label="Kc=0.5, SSD=1e-12, CH4%=1")
plt.plot(Altituded,COd,label="Kc=0.5, SSD=1e-12, CH4%=2")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("COAltVary.png")
plt.show()
plt.cla()