# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate as interpolate

Altitudea,SSDa,Tempa,Pressa,Rada,Metha,CO2a,H2a,CH4a,C2H2a,C2H6a,N2a,NH3a,CNa,HCNa,COa,H2Oa,H2COa,CH3OHa,NOa=np.genfromtxt("Triala.csv",delimiter=",",unpack=True)
Altitudeb,SSDb,Tempb,Pressb,Radb,Methb,CO2b,H2b,CH4b,C2H2b,C2H6b,N2b,NH3b,CNb,HCNb,COb,H2Ob,H2COb,CH3OHb,NOb=np.genfromtxt("Trialb.csv",delimiter=",",unpack=True)
Altitudec,SSDc,Tempc,Pressc,Radc,Methc,CO2c,H2c,CH4c,C2H2c,C2H6c,N2c,NH3c,CNc,HCNc,COc,H2Oc,H2COc,CH3OHc,NOc=np.genfromtxt("Trialc.csv",delimiter=",",unpack=True)
Altituded,SSDd,Tempd,Pressd,Radd,Methd,CO2d,H2d,CH4d,C2H2d,C2H6d,N2d,NH3d,CNd,HCNd,COd,H2Od,H2COd,CH3OHd,NOd=np.genfromtxt("Triald.csv",delimiter=",",unpack=True)

plt.plot(Altitudea,N2a,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,N2b,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,N2c,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,N2d,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("N2AltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,NH3a,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,NH3b,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,NH3c,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,NH3d,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH3AltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,NH3a,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,NH3b,label="Freezing with Aerosol Surfaces")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH3SurfacesAddition.png")
plt.show()
plt.cla()

plt.plot(Altitudea,HCNa,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,HCNb,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,HCNc,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,HCNd,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("HCNAltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,CNa,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,CNb,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,CNc,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,CNd,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("CNAltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,COa,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,COb,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,COc,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,COd,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("COAltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,CH4a,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,CH4b,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,CH4c,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,CH4d,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("CH4AltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudea,H2a,label="Freezing with No Aerosol Surfaces")
plt.plot(Altitudeb,H2b,label="Freezing with Aerosol Surfaces")
plt.plot(Altitudec,H2c,label="No Freezing with No Aerosol Surface")
plt.plot(Altituded,H2d,label="No Freezing with Aerosol Surface")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("H2AltVary.png")
plt.show()
plt.cla()

plt.plot(Altitudeb,CH4b,label="Methane")
plt.plot(Altitudeb,H2b,label="Hydrogen")
plt.plot(Altitudeb,N2b,label="Nitrogen")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("MainCompAerFrTit.png")
plt.show()
plt.cla()

plt.plot(Altitudeb,(CH4b/N2b),label="Methane")
plt.plot(Altitudeb,(H2b/N2b),label="Hydrogen")
plt.plot(Altitudeb,(N2b/N2b),label="Nitrogen")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("MainCompAerFrTitNormalised.png")
plt.show()
plt.cla()

plt.plot(Altitudea,(CH4a/N2a),label="Methane")
plt.plot(Altitudea,(H2a/N2a),label="Hydrogen")
plt.plot(Altitudea,(N2a/N2a),label="Nitrogen")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("MainCompFrTitNormalised.png")
plt.show()
plt.cla()

plt.plot(Altitudea,CH4a,label="Methane")
plt.plot(Altitudea,H2a,label="Hydrogen")
plt.plot(Altitudea,N2a,label="Nitrogen")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("MainCompFrTit.png")
plt.show()
plt.cla()

plt.plot(Altitudeb,(CH4b/N2b),label="Methane (CH4)")
plt.plot(Altitudeb,(H2b/N2b),label="Hydrogen (H2)")
plt.plot(Altitudeb,(N2b/N2b),label="Nitrogen (N2)")
plt.plot(Altitudeb,C2H6b/N2b,label="Ethane (C2H6)")
plt.plot(Altitudeb,COb/N2b,label="Carbon Monoxide (CO)")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("TraceAerFrTitNormalised.png")
plt.show()
plt.cla()

plt.plot(Altitudeb,(CH4a/N2a),label="Methane (CH4)")
plt.plot(Altitudeb,(H2a/N2a),label="Hydrogen (H2)")
plt.plot(Altitudeb,(N2a/N2a),label="Nitrogen (N2)")
plt.plot(Altitudeb,C2H6a/N2a,label="Ethane (C2H6)")
plt.plot(Altitudeb,COa/N2a,label="Carbon Monoxide (CO)")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("TraceFrTitNormalised.png")
plt.show()
plt.cla()

plt.plot(Altitudeb,C2H6b,label="Ethane (C2H6)")
plt.plot(Altitudeb,C2H2b,label="Acetylene (C2H2)")
plt.plot(Altitudeb,COb,label="Carbon Monoxide (CO)")
plt.plot(Altitudeb,CH3OHb,label="Methanol (CH3OH)")
plt.plot(Altitudeb,NOb,label="Nitrous Oxide (NO)")
plt.xlabel("Altitude (km)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("TraceAerFrTit.png")
plt.show()
plt.cla()

plt.plot(Tempb,Altitudeb)
plt.ylabel("Altitude (km)")
plt.xlabel(r"Temperature (K)")
plt.tight_layout()
plt.savefig("Altitude versus Temp.png",bbox_inches="tight")
plt.show()
plt.cla()
