
import numpy as np
import matplotlib.pyplot as plt

Tempa,Pressa,H2a,CH4a,C2H2a,C2H6a,N2a,NH3a,CNa,HCNa,COa,H2Oa,H2COa,CH3OHa,NOa=np.genfromtxt("TrialA.csv",delimiter=",",unpack=True)
Tempb,Pressb,H2b,CH4b,C2H2b,C2H6b,N2b,NH3b,CNb,HCNb,COb,H2Ob,H2COb,CH3OHb,NOb=np.genfromtxt("TrialB.csv",delimiter=",",unpack=True)
Tempc,Pressc,H2c,CH4c,C2H2c,C2H6c,N2c,NH3c,CNc,HCNc,COc,H2Oc,H2COc,CH3OHc,NOc=np.genfromtxt("TrialC.csv",delimiter=",",unpack=True)
Tempd,Pressd,H2d,CH4d,C2H2d,C2H6d,N2d,NH3d,CNd,HCNd,COd,H2Od,H2COd,CH3OHd,NOd=np.genfromtxt("TrialD.csv",delimiter=",",unpack=True)




plt.plot(Tempc,N2c,label="Aerosol Surfaces")
plt.plot(Tempd,N2d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("N2TempVary.png")
plt.savefig("N2TempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,N2a,label="Experimental Surfaces")
plt.plot(Tempb,N2b,label="No Surfaces")
plt.plot(Tempc,N2c,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("N2TempVary2.png")
plt.savefig("N2TempVary2.pdf")
plt.show()
plt.cla()

plt.plot(Tempc,CH4c,label="Aerosol Surfaces")
plt.plot(Tempd,CH4d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("CH4TempVary.png")
plt.savefig("CH4TempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,CH4a,label="Experimental Surfaces")
plt.plot(Tempb,CH4b,label="No Surfaces")
plt.plot(Tempc,CH4c,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("CH4TempVary2.png")
plt.savefig("CH4TempVary2.pdf")
plt.show()
plt.cla()

plt.plot(Tempc,H2c,label="Aerosol Surfaces")
plt.plot(Tempd,H2d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("H2TempVary.png")
plt.savefig("H2TempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,H2a,label="Experimental Surfaces")
plt.plot(Tempb,H2b,label="No Surfaces")
plt.plot(Tempc,H2c,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("H2TempVary2.png")
plt.savefig("H2TempVary2.pdf")
plt.show()
plt.cla()

plt.plot(Tempc,NH3c,label="Aerosol Surfaces")
plt.plot(Tempd,NH3d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH3TempVary.png")
plt.savefig("NH3TempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,NH3a,label="Experimental Surfaces")
plt.plot(Tempb,NH3b,label="No Surfaces")
plt.plot(Tempc,NH3c,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH3TempVary2.png")
plt.savefig("NH3TempVary2.pdf")
plt.show()
plt.cla()

plt.plot(Tempc,C2H2c,label="Aerosol Surfaces")
plt.plot(Tempd,C2H2d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("C2H2TempVary.png")
plt.savefig("C2H2TempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,C2H2a,label="Experimental Surfaces")
plt.plot(Tempb,C2H2b,label="No Surfaces")
plt.plot(Tempc,C2H2c,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("C2H2TempVary2.png")
plt.savefig("C2H2TempVary2.pdf")
plt.show()
plt.cla()

plt.plot(Tempc,C2H6c,label="Aerosol Surfaces")
plt.plot(Tempd,C2H6d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("C2H6TempVary.png")
plt.savefig("C2H6TempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,C2H6a,label="Experimental Surfaces")
plt.plot(Tempb,C2H6b,label="No Surfaces")
plt.plot(Tempc,C2H6c,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("C2H6TempVary2.png")
plt.savefig("C2H6TempVary2.pdf")
plt.show()
plt.cla()

plt.plot(Tempc,HCNc,label="Aerosol Surfaces")
plt.plot(Tempd,HCNd,label="Aerosol Surfaces and Freezing")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("HCNTempVary.png")
plt.savefig("HCNTempVary.pdf")
plt.show()
plt.cla()

plt.plot(Tempa,HCNa,label="Experimental Surfaces")
plt.plot(Tempb,HCNb,label="No Surfaces")
plt.plot(Tempc,HCNc,label="Aerosol Surfaces")
plt.xlabel("Temperature (K)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("HCNTempVary2.png")
plt.savefig("HCNTempVary2.pdf")
plt.show()
plt.cla()

