
import numpy as np
import matplotlib.pyplot as plt

CH4,H2,C2H2,C2H6,NH2,NH3,CN,HCN,CH3CN,C6H6,H2CO,CH3OH,NO=np.genfromtxt("CH4SurfFreezeHCNNormalised.csv",delimiter=",",unpack=True)

 
plt.plot(CH4,(HCN/np.max(HCN)),label="HCN")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u)")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeHCNnormalHCN.pdf")
plt.show()
plt.cla()

plt.plot(CH4,(NH2/np.max(HCN)),label="NH2")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u)")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeNH2normalHCN.pdf")
plt.show()
plt.cla()

plt.plot(CH4,(NH3/np.max(HCN)),label="NH3")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u)")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeNH3normalHCN.pdf")
plt.show()
plt.cla()

plt.plot(CH4,(CN/np.max(HCN)),label="CN")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u)")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeCNnormalHCN.pdf")
plt.show()
plt.cla()

plt.plot(CH4,(CH3CN/np.max(HCN)),label="CH3CN")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u)")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeCH3CNnormalHCN.pdf")
plt.show()
plt.cla()

plt.plot(CH4,(C6H6/np.max(HCN)),label="C6H6")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u))")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeC6H6normalHCN.pdf")
plt.show()
plt.cla()

plt.plot(CH4,(C2H2/np.max(HCN)),label="C2H2")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Intensity, (a.u)")
plt.legend()
#plt.yscale("log")
plt.savefig("CH4ChangeC2H2normalHCN.pdf")
plt.show()
plt.cla()