
import numpy as np
import matplotlib.pyplot as plt

CH4,H2,C2H2,C2H6,NH2,NH3,CN,HCN,CH3CN,C6H6,H2CO,CH3OH,NO=np.genfromtxt("CH4SurfFreeze.csv",delimiter=",",unpack=True)

 
plt.plot(CH4,HCN,label="HCN")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeHCNlog.png")
plt.show()
plt.cla()

plt.plot(CH4,NH2,label="NH2")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeNH2log.png")
plt.show()
plt.cla()

plt.plot(CH4,NH3,label="NH3")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeNH3log.png")
plt.show()
plt.cla()

plt.plot(CH4,CN,label="CN")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeCNlog.png")
plt.show()
plt.cla()

plt.plot(CH4,CH3CN,label="CH3CN")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeCH3CNlog.png")
plt.show()
plt.cla()

plt.plot(CH4,C6H6,label="C6H6")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeC6H6log.png")
plt.show()
plt.cla()

plt.plot(CH4,C2H2,label="C2H2")
plt.xlabel("CH4 Composition (%)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.savefig("CH4ChangeC2H2log.png")
plt.show()
plt.cla()