
import numpy as np
import matplotlib.pyplot as plt

Tempa,Pressa,H2a,CH4a,C2H2a,C2H6a,N2a,NH3a,CNa,HCNa,COa,H2Oa,H2COa,CH3OHa,NOa=np.genfromtxt("TrialA.csv",delimiter=",",unpack=True)
Tempb,Pressb,H2b,CH4b,C2H2b,C2H6b,N2b,NH3b,CNb,HCNb,COb,H2Ob,H2COb,CH3OHb,NOb=np.genfromtxt("TrialB.csv",delimiter=",",unpack=True)
Tempc,Pressc,H2c,CH4c,C2H2c,C2H6c,N2c,NH3c,CNc,HCNc,COc,H2Oc,H2COc,CH3OHc,NOc=np.genfromtxt("TrialC.csv",delimiter=",",unpack=True)
Tempd,Pressd,H2d,CH4d,C2H2d,C2H6d,N2d,NH3d,CNd,HCNd,COd,H2Od,H2COd,CH3OHd,NOd=np.genfromtxt("TrialD.csv",delimiter=",",unpack=True)



plt.plot(Pressa,N2a,label="Experimental Surfaces")
plt.plot(Pressb,N2b,label="No Surfaces")
plt.plot(Pressc,N2c,label="Aerosol Surfaces")
plt.plot(Pressd,N2d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("N2PressVary.png")
plt.savefig("N2PressVary.pdf")
plt.show()
plt.cla()

plt.plot(Pressa,CH4a,label="Experimental Surfaces")
plt.plot(Pressb,CH4b,label="No Surfaces")
plt.plot(Pressc,CH4c,label="Aerosol Surfaces")
plt.plot(Pressd,CH4d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("CH4PressVary.png")
plt.savefig("CH4PressVary.pdf")
plt.show()
plt.cla()

plt.plot(Pressa,H2a,label="Experimental Surfaces")
plt.plot(Pressb,H2b,label="No Surfaces")
plt.plot(Pressc,H2c,label="Aerosol Surfaces")
plt.plot(Pressd,H2d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("H2PressVary.png")
plt.savefig("H2PressVary.pdf")
plt.show()
plt.cla()

plt.plot(Pressa,NH3a,label="Experimental Surfaces")
plt.plot(Pressb,NH3b,label="No Surfaces")
plt.plot(Pressc,NH3c,label="Aerosol Surfaces")
plt.plot(Pressd,NH3d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("NH3PressVary.png")
plt.savefig("NH3PressVary.pdf")
plt.show()
plt.cla()


plt.plot(Pressa,C2H2a,label="Experimental Surfaces")
plt.plot(Pressb,C2H2b,label="No Surfaces")
plt.plot(Pressc,C2H2c,label="Aerosol Surfaces")
plt.plot(Pressd,C2H2d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("C2H2PressVary.png")
plt.savefig("C2H2PressVary.pdf")
plt.show()
plt.cla()

plt.plot(Pressa,C2H6a,label="Experimental Surfaces")
plt.plot(Pressb,C2H6b,label="No Surfaces")
plt.plot(Pressc,C2H6c,label="Aerosol Surfaces")
plt.plot(Pressd,C2H6d,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("C2H6PressVary.png")
plt.savefig("C2H6PressVary.pdf")
plt.show()
plt.cla()

plt.plot(Pressa,HCNa,label="Experimental Surfaces")
plt.plot(Pressb,HCNb,label="No Surfaces")
plt.plot(Pressc,HCNc,label="Aerosol Surfaces")
plt.plot(Pressd,HCNd,label="Aerosol Surfaces and Freezing")
plt.xlabel("Pressure (kPa)")
plt.ylabel(r"Concentration, n (cm$^{-3}$)")
plt.legend()
plt.yscale("log")
plt.tight_layout()
plt.savefig("HCNPressVary.png")
plt.savefig("HCNPressVary.pdf")
plt.show()
plt.cla()


